//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ahorro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ahorro()
        {
            this.Depositoes = new HashSet<Deposito>();
        }
    
        public int ahorroID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public decimal montoMensual { get; set; }
        public System.DateTime fechaInicial { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposito> Depositoes { get; set; }
        public virtual ProgresoAhorro ProgresoAhorro { get; set; }
    }
}
