//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class Ahorro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ahorro()
        {
            this.Depositoes = new HashSet<Deposito>();
        }

        public int ahorroID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public decimal montoMensual { get; set; }
        public System.DateTime fechaInicial { get; set; }

        [JsonIgnore]
        public virtual Cliente Cliente { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Deposito> Depositoes { get; set; }

        [JsonIgnore]
        public virtual ProgresoAhorro ProgresoAhorro { get; set; }
    }
}
