//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSuperEntities : DbContext
    {
        public DBSuperEntities()
            : base("name=DBSuperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ahorro> Ahorros { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Deposito> Depositoes { get; set; }
        public virtual DbSet<DetalleLiquidacion> DetalleLiquidacions { get; set; }
        public virtual DbSet<EstadoPrestamo> EstadoPrestamoes { get; set; }
        public virtual DbSet<Liquidacione> Liquidaciones { get; set; }
        public virtual DbSet<Movimiento> Movimientos { get; set; }
        public virtual DbSet<Multa> Multas { get; set; }
        public virtual DbSet<PagoPrestamo> PagoPrestamoes { get; set; }
        public virtual DbSet<Prestamo> Prestamos { get; set; }
        public virtual DbSet<ProgresoAhorro> ProgresoAhorroes { get; set; }
        public virtual DbSet<ProgresoPrestamo> ProgresoPrestamoes { get; set; }
        public virtual DbSet<RolesUsuario> RolesUsuarios { get; set; }
        public virtual DbSet<TasaIntere> TasaInteres { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
