//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization; // Asegúrate de incluir esta línea

namespace Natillera1.Models
{
    public partial class Liquidacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liquidacione()
        {
            this.DetalleLiquidacions = new HashSet<DetalleLiquidacion>();
        }

        public int liquidacionID { get; set; }
        public int? clienteID { get; set; } // Cambié a int? para usar Nullable<int>
        public DateTime fecha { get; set; }
        public decimal montoTotal { get; set; }
        public string descripcion { get; set; }

        public virtual Cliente Cliente { get; set; }

        [JsonIgnore] // Ignora esta colección en la serialización JSON
        public virtual ICollection<DetalleLiquidacion> DetalleLiquidacions { get; set; }
    }
}
