//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.PagoPrestamoes = new HashSet<PagoPrestamo>();
        }
    
        public int prestamoID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public decimal montoSolicitado { get; set; }
        public Nullable<int> tasaInteresID { get; set; }
        public Nullable<int> estadoPrestamoID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoPrestamo EstadoPrestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoPrestamo> PagoPrestamoes { get; set; }
        public virtual TasaIntere TasaIntere { get; set; }
        public virtual ProgresoPrestamo ProgresoPrestamo { get; set; }
    }
}
