//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization; // Asegúrate de incluir esta línea

namespace Natillera1.Models
{
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.PagoPrestamoes = new HashSet<PagoPrestamo>();
        }

        public int prestamoID { get; set; }
        public int? clienteID { get; set; } // Cambié a int? para usar Nullable<int>
        public DateTime fechaSolicitud { get; set; }
        public decimal montoSolicitado { get; set; }
        public int? tasaInteresID { get; set; } // Cambié a int? para usar Nullable<int>
        public int? estadoPrestamoID { get; set; } // Cambié a int? para usar Nullable<int>

        [JsonIgnore] // Ignora esta propiedad en la serialización JSON si no deseas incluirla
        public virtual Cliente Cliente { get; set; }

        [JsonIgnore] // Ignora esta propiedad en la serialización JSON si no deseas incluirla
        public virtual EstadoPrestamo EstadoPrestamo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoPrestamo> PagoPrestamoes { get; set; }

        [JsonIgnore] // Ignora esta propiedad en la serialización JSON si no deseas incluirla
        public virtual TasaIntere TasaIntere { get; set; }

        [JsonIgnore] // Ignora esta propiedad en la serialización JSON si no deseas incluirla
        public virtual ProgresoPrestamo ProgresoPrestamo { get; set; }
    }
}
