//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.PagoPrestamos = new HashSet<PagoPrestamo>();
        }
    
        public int prestamoID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public decimal montoSolicitado { get; set; }
        public Nullable<int> tasaInteresID { get; set; }
        public Nullable<int> estadoPrestamoID { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoPrestamo EstadoPrestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoPrestamo> PagoPrestamos { get; set; }
        public virtual TasaIntere TasaIntere { get; set; }
        public virtual ProgresoPrestamo ProgresoPrestamo { get; set; }
    }
}
