//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization; // Asegúrate de incluir esta línea

namespace Natillera1.Models
{
    public partial class ProgresoPrestamo
    {
        public int prestamoID { get; set; }
        public int? clienteID { get; set; } // Cambié a int? para usar Nullable<int>
        public decimal montoPendiente { get; set; }
        public decimal montoPagado { get; set; }

        [JsonIgnore] // Ignora esta propiedad en la serialización JSON si no deseas incluirla
        public virtual Cliente Cliente { get; set; }

        [JsonIgnore] // Ignora esta propiedad en la serialización JSON si no deseas incluirla
        public virtual Prestamo Prestamo { get; set; }
    }
}
