//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgresoPrestamo
    {
        public int prestamoID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public decimal montoPendiente { get; set; }
        public decimal montoPagado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Prestamo Prestamo { get; set; }
    }
}
