//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgresoAhorro
    {
        public int ahorroID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public int numeroPagos { get; set; }
        public decimal totalMonto { get; set; }
    
        public virtual Ahorro Ahorro { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
