//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization; // Asegúrate de tener esto para JsonIgnore

    public partial class sysdiagram
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }

        [JsonIgnore] // Opcional: ignora esta propiedad si no quieres que se serialice
        public byte[] definition { get; set; }
    }
}
