//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization; // Asegúrate de tener esto para JsonIgnore

    public partial class Usuario
    {
        public int usuarioID { get; set; }
        public string nombreUsuario { get; set; }
        public string password { get; set; }
        public Nullable<int> rolID { get; set; }

        [JsonIgnore] // Ignora esta propiedad para evitar referencia circular
        public virtual RolesUsuario RolesUsuario { get; set; }
    }
}
